title: Sentence Concreteness
description: How much information should a headline reveal?
logo: /assets/images/concreteness-logo.jpg
cornelltechlogo: /assets/images/cornell-tech-logo.png
cornelllogo: /assets/images/cornell-cals-logo.png
theme: jekyll-theme-minimal
twitter:
  card: summary_large_image
